//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THN.Core.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSetting
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyAddress2 { get; set; }
        public string CompanyTel { get; set; }
        public string CompanyTel1 { get; set; }
        public string CompanyTel2 { get; set; }
        public string HotPhone { get; set; }
        public string HotPhone2 { get; set; }
        public string Email { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string NameShort { get; set; }
        public string Owner { get; set; }
        public Nullable<int> TaxCode { get; set; }
        public string DefaultTitle { get; set; }
        public string PageTitleSEO { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public string Logo { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string YoutubeUrl { get; set; }
        public string GooglePlusUrl { get; set; }
    }
}
