//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THN.Core.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportCustomer
    {
        public int ID { get; set; }
        public string Supporter { get; set; }
        public string Telphone { get; set; }
        public string Skype { get; set; }
        public string Orther { get; set; }
    }
}
